[package]
name = "latex2mathml-web"
version = "0.1.0"
authors = ["Hiromu Sugiura <h.sugiura0705@outlook.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
latex2mathml = "0.2.2"
